import numpy as np
a = np.array([1, 2, 3])
b = np.zeros((3,4))
c = np.ones((2,3))
d = np.arange(1,10,2)
e = np.linspace(0,1,5)
f = np.random.rand(3,3)
g = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
